-- Script tạo bảng YEUCAU_THAYDOI_NHANKHAU
USE household_management;
GO

-- Tạo bảng nếu chưa tồn tại
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[YEUCU_THAYDOI_NHANKHAU]') AND type in (N'U'))
BEGIN
    CREATE TABLE YEUCU_THAYDOI_NHANKHAU (
        MAYEUCAU INT IDENTITY(1,1) PRIMARY KEY,
        MATAIKHOAN INT NOT NULL,
        LOAIYEUCU VARCHAR(20) NOT NULL, -- 'THEM', 'SUA', 'XOA'
        MANHANKHAU INT NULL,
        DULIEU TEXT NULL, -- JSON string chứa dữ liệu nhân khẩu
        TRANGTHAI VARCHAR(50) NOT NULL DEFAULT 'CHO_XAC_THUC', -- 'CHO_XAC_THUC', 'DA_XAC_THUC', 'TU_CHOI'
        GHICHU TEXT NULL,
        LYDOTUCHOI TEXT NULL,
        MACANBO_XACTHUC INT NULL,
        NGAYXACTHUC DATETIME NULL,
        NGAYTAO DATETIME DEFAULT GETDATE(),
        
        FOREIGN KEY (MATAIKHOAN) REFERENCES TAIKHOAN(MATAIKHOAN),
        FOREIGN KEY (MANHANKHAU) REFERENCES NHANKHAU(MANHANKHAU),
        FOREIGN KEY (MACANBO_XACTHUC) REFERENCES CANBO(MACANBO),
        
        CONSTRAINT CHK_LOAIYEUCU CHECK (LOAIYEUCU IN ('THEM', 'SUA', 'XOA')),
        CONSTRAINT CHK_TRANGTHAI CHECK (TRANGTHAI IN ('CHO_XAC_THUC', 'DA_XAC_THUC', 'TU_CHOI'))
    );
    
    PRINT 'Đã tạo bảng YEUCU_THAYDOI_NHANKHAU';
END
ELSE
BEGIN
    PRINT 'Bảng YEUCU_THAYDOI_NHANKHAU đã tồn tại';
END
GO






