-- Script tạo bảng YEUCU_THAYDOI_NHANKHAU cho MySQL
USE household_management;

-- Tạo bảng nếu chưa tồn tại
CREATE TABLE IF NOT EXISTS YEUCU_THAYDOI_NHANKHAU (
    MAYEUCAU INT AUTO_INCREMENT PRIMARY KEY,
    MATAIKHOAN INT NOT NULL,
    LOAIYEUCU VARCHAR(20) NOT NULL, -- 'THEM', 'SUA', 'XOA'
    MANHANKHAU INT NULL,
    DULIEU TEXT NULL, -- JSON string chứa dữ liệu nhân khẩu
    TRANGTHAI VARCHAR(50) NOT NULL DEFAULT 'CHO_XAC_THUC', -- 'CHO_XAC_THUC', 'DA_DUYET', 'DA_TU_CHOI'
    GHICHU TEXT NULL,
    LYDOTUCHOI TEXT NULL,
    MACANBO_XACTHUC INT NULL,
    NGAYXACTHUC DATETIME NULL,
    NGAYTAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (MATAIKHOAN) REFERENCES TAIKHOAN(MATAIKHOAN),
    FOREIGN KEY (MANHANKHAU) REFERENCES NHANKHAU(MANHANKHAU),
    FOREIGN KEY (MACANBO_XACTHUC) REFERENCES CANBO(MACANBO),
    
    CONSTRAINT CHK_LOAIYEUCU CHECK (LOAIYEUCU IN ('THEM', 'SUA', 'XOA')),
    CONSTRAINT CHK_TRANGTHAI CHECK (TRANGTHAI IN ('CHO_XAC_THUC', 'DA_DUYET', 'DA_TU_CHOI'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;






