-- =============================================
-- Script MySQL cho hệ thống quản lý hộ khẩu
-- =============================================

CREATE DATABASE IF NOT EXISTS household_management CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE household_management;

-- =============================================
-- 1. TẠO CÁC BẢNG ĐỊA CHỈ
-- =============================================

CREATE TABLE IF NOT EXISTS THANHPHO (
    MATHANHPHO INT AUTO_INCREMENT PRIMARY KEY,
    TENTHANHPHO VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS QUANHUYEN (
    MAQUANHUYEN INT AUTO_INCREMENT PRIMARY KEY,
    TENQUANHUYEN VARCHAR(100),
    MATHANHPHO INT,
    FOREIGN KEY (MATHANHPHO) REFERENCES THANHPHO(MATHANHPHO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS XAPHUONG (
    MAXAPHUONG INT AUTO_INCREMENT PRIMARY KEY,
    TENXAPHUONG VARCHAR(100),
    MAQUANHUYEN INT,
    FOREIGN KEY (MAQUANHUYEN) REFERENCES QUANHUYEN(MAQUANHUYEN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================
-- 2. TẠO BẢNG HỘ KHẨU VÀ NHÂN KHẨU
-- =============================================

CREATE TABLE IF NOT EXISTS HOKHAU (
    SOHOKHAU INT AUTO_INCREMENT PRIMARY KEY,
    DIACHI TEXT,
    MAXAPHUONG INT,
    NGAYCAP DATE,
    GHICHU TEXT,
    FOREIGN KEY (MAXAPHUONG) REFERENCES XAPHUONG(MAXAPHUONG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS NHANKHAU (
    MANHANKHAU INT AUTO_INCREMENT PRIMARY KEY,
    SOHOKHAU INT,
    HOTEN VARCHAR(100),
    GIOITINH VARCHAR(10),
    NGAYSINH DATE,
    NGHENGHIEP VARCHAR(100),
    QUANHEVOICHUHO VARCHAR(50),
    TRANGTHAI VARCHAR(50) DEFAULT 'Thường trú',
    CMND VARCHAR(20) NULL,
    NOITHUONGTRUCHUYENDEN VARCHAR(200) NULL,
    NGAYCHUYENDI DATETIME NULL,
    NOICHUYEN VARCHAR(200) NULL,
    GHICHU TEXT NULL,
    FOREIGN KEY (SOHOKHAU) REFERENCES HOKHAU(SOHOKHAU)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================
-- 3. TẠO BẢNG THÔNG TIN LIÊN LẠC
-- =============================================

CREATE TABLE IF NOT EXISTS ContactInfo (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    MaNhanKhau INT,
    Type VARCHAR(20),
    Value VARCHAR(255),
    IsPrimary TINYINT(1) DEFAULT 0,
    FOREIGN KEY (MaNhanKhau) REFERENCES NHANKHAU(MANHANKHAU)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_contact_nhankhau_type ON ContactInfo (MaNhanKhau, Type);
CREATE INDEX idx_contact_primary ON ContactInfo (MaNhanKhau, IsPrimary);

-- =============================================
-- 4. TẠO BẢNG BIẾN ĐỘNG NHÂN KHẨU
-- =============================================

CREATE TABLE IF NOT EXISTS BIENDONGNHANKHAU (
    MABIENDONG INT AUTO_INCREMENT PRIMARY KEY,
    MANHANKHAU INT,
    LOAIBIENDONG VARCHAR(50),
    NGAYBATDAU DATE,
    NGAYKETTHUC DATE,
    LYDODOICHUYENDI TEXT,
    FOREIGN KEY (MANHANKHAU) REFERENCES NHANKHAU(MANHANKHAU)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================
-- 5. TẠO BẢNG GIẤY TỜ
-- =============================================

CREATE TABLE IF NOT EXISTS GIAYTO (
    MAGIAYTO INT AUTO_INCREMENT PRIMARY KEY,
    MANHANKHAU INT,
    LOAIGIAYTO VARCHAR(50),
    SOGIAYTO VARCHAR(50),
    NGAYCAP DATE,
    NOICAP VARCHAR(100),
    FOREIGN KEY (MANHANKHAU) REFERENCES NHANKHAU(MANHANKHAU)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================
-- 6. TẠO BẢNG CÁN BỘ VÀ TÀI KHOẢN
-- =============================================

CREATE TABLE IF NOT EXISTS CANBO (
    MACANBO INT AUTO_INCREMENT PRIMARY KEY,
    HOTEN VARCHAR(100),
    CHUCVU VARCHAR(50),
    MAXAPHUONG INT,
    FOREIGN KEY (MAXAPHUONG) REFERENCES XAPHUONG(MAXAPHUONG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS TAIKHOAN (
    MATAIKHOAN INT AUTO_INCREMENT PRIMARY KEY,
    MACANBO INT NULL,
    MANHANKHAU INT NULL,
    TENDANGNHAP VARCHAR(50) UNIQUE,
    MATKHAU VARCHAR(100),
    VAITRO VARCHAR(50),
    EMAIL VARCHAR(100) UNIQUE,
    TRANGTHAI VARCHAR(50) DEFAULT 'CHO_KICH_HOAT',
    FOREIGN KEY (MACANBO) REFERENCES CANBO(MACANBO),
    FOREIGN KEY (MANHANKHAU) REFERENCES NHANKHAU(MANHANKHAU)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================
-- 7. TẠO BẢNG THU PHÍ - ĐÓNG GÓP
-- =============================================

CREATE TABLE IF NOT EXISTS LOAIPHI (
    MALOAI INT AUTO_INCREMENT PRIMARY KEY,
    TENLOAIPHI VARCHAR(100),
    MOTA TEXT,
    BATBUOC TINYINT(1) DEFAULT 0,
    DINHMUC DECIMAL(12,2),
    CONSTRAINT uniq_tenloaiphi UNIQUE (TENLOAIPHI)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS DOTTHU (
    MADOTTHU INT AUTO_INCREMENT PRIMARY KEY,
    TENDOTTHU VARCHAR(100),
    NGAYBATDAU DATE,
    NGAYKETTHUC DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS THUPHI (
    MATHUPHI INT AUTO_INCREMENT PRIMARY KEY,
    SOHOKHAU INT,
    MADOTTHU INT,
    MALOAI INT,
    SOTIEN DECIMAL(12,2),
    NGAYDONG DATE,
    GHICHU TEXT,
    FOREIGN KEY (SOHOKHAU) REFERENCES HOKHAU(SOHOKHAU),
    FOREIGN KEY (MADOTTHU) REFERENCES DOTTHU(MADOTTHU),
    FOREIGN KEY (MALOAI) REFERENCES LOAIPHI(MALOAI)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_thuphi_ho_dot_loai ON THUPHI (SOHOKHAU, MADOTTHU, MALOAI);

-- =============================================
-- 8. TẠO BẢNG TẠM TRÚ - TẠM VẮNG
-- =============================================

CREATE TABLE IF NOT EXISTS TamTru (
    MaTamTru INT AUTO_INCREMENT PRIMARY KEY,
    MaNhanKhau INT,
    NoiTamTru VARCHAR(255),
    TuNgay DATETIME,
    DenNgay DATETIME NULL,
    LyDo TEXT,
    TrangThai VARCHAR(50) DEFAULT 'Đang tạm trú',
    GhiChu TEXT,
    FOREIGN KEY (MaNhanKhau) REFERENCES NHANKHAU(MANHANKHAU)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_tamtru_nhankhau_ngay ON TamTru (MaNhanKhau, TuNgay);

CREATE TABLE IF NOT EXISTS TamVang (
    MaTamVang INT AUTO_INCREMENT PRIMARY KEY,
    MaNhanKhau INT,
    NoiDi VARCHAR(255),
    TuNgay DATETIME,
    DenNgay DATETIME NULL,
    LyDo TEXT,
    TrangThai VARCHAR(50) DEFAULT 'Dang tam vang',
    GhiChu TEXT,
    FOREIGN KEY (MaNhanKhau) REFERENCES NHANKHAU(MANHANKHAU)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_tamvang_nhankhau_ngay ON TamVang (MaNhanKhau, TuNgay);

-- =============================================
-- 9. TẠO BẢNG LỊCH SỬ THAY ĐỔI
-- =============================================

CREATE TABLE IF NOT EXISTS LICHSU_THAYDOI_NHANKHAU (
    MALICHSUTHAYDOI INT AUTO_INCREMENT PRIMARY KEY,
    MANHANKHAU INT NOT NULL,
    LOAITHAYDOI VARCHAR(50) NULL,
    NOIDUNGTHAYDOI TEXT NULL,
    NGAYTHAYDOI DATETIME NOT NULL,
    GHICHU TEXT NULL,
    FOREIGN KEY (MANHANKHAU) REFERENCES NHANKHAU(MANHANKHAU) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IX_LICHSU_NHANKHAU_MANHANKHAU ON LICHSU_THAYDOI_NHANKHAU(MANHANKHAU);
CREATE INDEX IX_LICHSU_NHANKHAU_NGAYTHAYDOI ON LICHSU_THAYDOI_NHANKHAU(NGAYTHAYDOI DESC);

CREATE TABLE IF NOT EXISTS LICHSU_THAYDOI_HOKHAU (
    MALICHSUTHAYDOI INT AUTO_INCREMENT PRIMARY KEY,
    SOHOKHAU INT NOT NULL,
    NOIDUNGTHAYDOI TEXT NULL,
    NGAYTHAYDOI DATETIME NOT NULL,
    GHICHU TEXT NULL,
    FOREIGN KEY (SOHOKHAU) REFERENCES HOKHAU(SOHOKHAU) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IX_LICHSU_HOKHAU_SOHOKHAU ON LICHSU_THAYDOI_HOKHAU(SOHOKHAU);
CREATE INDEX IX_LICHSU_HOKHAU_NGAYTHAYDOI ON LICHSU_THAYDOI_HOKHAU(NGAYTHAYDOI DESC);

-- =============================================
-- 10. TẠO VIEW HỖ TRỢ
-- =============================================

CREATE OR REPLACE VIEW VW_NHANKHAU_CHITIET AS
SELECT 
    nk.MANHANKHAU,
    nk.HOTEN,
    nk.GIOITINH,
    nk.NGAYSINH,
    nk.NGHENGHIEP,
    nk.QUANHEVOICHUHO,
    nk.TRANGTHAI,
    nk.CMND,
    nk.NOITHUONGTRUCHUYENDEN,
    nk.NGAYCHUYENDI,
    nk.NOICHUYEN,
    nk.GHICHU,
    hk.SOHOKHAU,
    hk.DIACHI,
    hk.NGAYCAP,
    xp.TENXAPHUONG
FROM NHANKHAU nk
INNER JOIN HOKHAU hk ON nk.SOHOKHAU = hk.SOHOKHAU
INNER JOIN XAPHUONG xp ON hk.MAXAPHUONG = xp.MAXAPHUONG;
